[package]
name = "docker_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "2.3.0"
crossterm = "0.28.1"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
